### ISSUE TITLE
inscription_feed error!

### ISSUE THREAD

**Issue by pupudaye** [hirosystems/chainhook#329]
### Prerequisites

- [X] I have [searched](https://github.com/hirosystems/.github/issues) for duplicate or closed issues
- [X] I understand the [code of conduct](https://github.com/hirosystems/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] I have read the [contributing guidelines](https://github.com/hirosystems/.github/blob/main/CONTRIBUTING.md)

### Describe the issue

chainhook-node  | {"msg":"Trigger http://172.20.0.6:3099/chainhook/inscription_feed failed with status 500 Internal Server Error","level":"WARN","ts":"2023-07-12T02:50:31.904950704Z"}
chainhook-node  | {"msg":"unable to send request after several retries","level":"ERRO","ts":"2023-07-12T02:50:31.904977795Z"}
chainhook-node  | {"msg":"Initial ingestion failing","level":"ERRO","ts":"2023-07-12T02:50:31.909487451Z"}
chainhook-node  | {"msg":"Trigger http://172.20.0.6:3099/chainhook/inscription_feed failed with status 500 Internal Server Error","level":"WARN","ts":"2023-07-12T02:50:31.932226621Z"}

### What operating system(s) are you seeing the problem on?

Linux

### What version are you using?

chainhook 0.16.0

**Comment by pupudaye** [comment]
this is ordinals-api service logs

ordinals-api  | {"level":"info","time":"2023-07-12T02:55:20.503Z","pid":1,"hostname":"62c193d5520d","name":"ordinals-api","reqId":"req-8a1","res":{"statusCode":500},"responseTime":4.202715992927551,"msg":"request completed"}
ordinals-api  | {"level":"error","time":"2023-07-12T02:55:20.503Z","pid":1,"hostname":"62c193d5520d","name":"ordinals-api","err":{"type":"Error","message":"Unable to process invalid chainhook payload","stack":"Error: Unable to process invalid chainhook payload\n    at processInscriptionFeed (/app/dist/src/chainhook/helpers.js:15:15)\n    at Object.<anonymous> (/app/dist/src/chainhook/server.js:107:56)\n    at preHandlerCallback (/app/node_modules/fastify/lib/handleRequest.js:128:37)\n    at next (/app/node_modules/fastify/lib/hooks.js:176:7)\n    at handleResolve (/app/node_modules/fastify/lib/hooks.js:193:5)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"},"msg":"EventServer error processing inscription_feed"}
